import type { Metadata } from "next";
import { Inter, Sen } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const sen = Sen({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en dark">
      <body className={`${sen.className}`}>
        <main className="font-s min-h-screen">{children}</main>
      </body>
    </html>
  );
}
